name: defonteincoevorden
favicon: null
layout_spectrum: 0.74288
typography_spectrum: 0.50089
title: De Fontein
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#616c60'
    - '#18cc33'
    - '#a6aca5'
    - '#98e8a4'
  brandStrength: 0.75
  lightness: 0.6131173139438033
  saturation: 0.4991942385677248
  rhythmicContrast: 0.5875249793753028
purpose: []
