name: defonteincoevorden
favicon: null
layout_spectrum: 1
typography_spectrum: 0.00181
title: De Fontein
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8e8e8'
    - '#060000'
    - '#dbb6a6'
    - '#452820'
    - '#a47e75'
  brandStrength: 0.2345877957995981
  lightness: 0.6131173139438033
  saturation: 0.4991942385677248
  rhythmicContrast: 0.5875249793753028
purpose: []
